### ISSUE TITLE
[Feat] Object detection + object tracking 코드 작성

### ISSUE THREAD

**Issue by garlicvread** [ADA-1st-macro-walikngAssistant/yolov7_with_object_tracking#4]
- [x] 깃이그노어 파일 작성: MacOS, Windows, Linux, Python, PyCharm, IntelliJ IDEA
- [x] 기존 yolov7 프로젝트에서 detect.py 복사
- [x] Object sorting을 위한 sort.py 추가
- [x] 바운딩 박스에 오브젝트 루트 추가 코드 작성

**Comment by garlicvread** [comment]
Close with #7, #8
